### ISSUE TITLE
Define a standardized format for map issues

### ISSUE THREAD

**Issue by planemad** [osmlab/to-fix#150]
Currently to-fix has [hardcoded logic](https://github.com/osmlab/to-fix/blob/gh-pages/src/components/task.js) to read from various sources of [CSV error streams](https://github.com/osmlab/to-fix/wiki/Task%20sources). This does not scale well, and thought a better approach might be to define a standard spec for QA reporting tools to generate issues. Benefits:
- Map QA APIs that can talk to each other
- Allow any micro tasking QA tool to interpret issues from any source
- Help expand the ecosystem of QA tools for more varied approaches and ultimately a better map

Went through some of the popular QA tools to understand the existing specs:
- [maproulette challenge](https://github.com/maproulette/maproulette2/wiki/Introducing-New-MapRoulette---Part-1.-Creating-and-Maintaining-Challenges)
- [osmose API](http://wiki.openstreetmap.org/wiki/Osmose#APIs)
- [keepright](http://keepright.at)
- [to-fix project](https://github.com/osmlab/to-fix/wiki/Task%20sources)

It seems like there are three useful ways to generate issues from OSM data:
- Postgres -> CSV
- Overpass -> Geojson
- [osmlint](https://github.com/osmlab/osmlint) -> Geojson

CSV is a nice natural format for a listing of issues.
### Map QA issue spec

**Draft** https://gist.github.com/planemad/9e2a010ce5fcdefb38192dd63e925968

Not sure if this all makes sense, but this has been chewing my head for a while and had to put it out. Now I can 😴 

cc @mvexel @mueschel @jocelynj @Rub21 @aaronlidman @batpad @ajithranka @maning

**Comment by aaronlidman** [comment]
I think to-fix should use GeoJSON. GeoJSON should be the standard.

We decided on CSV for a couple of reasons which no longer hold up:
- we were mostly using keepright data
- we were not primarily using spatial data but tabular data with references to osm ids
- to import millions of items into Postgres as fast as possible with `COPY`

Now:
- we almost entirely provide our own data from osmlint or other sources
- the data we're generating is almost always line-delimited GeoJSON
- we have better tooling around line-delimited GeoJSON like tippecanoe and other CLI tools
  - these tools will only become more numerous
- we should write a tool to stream data into Postgres quickly, relying on [pg-copy-streams](https://github.com/brianc/node-pg-copy-streams)

If we define a spec it should be as simple as the [simplestyle-spec](https://github.com/mapbox/simplestyle-spec) (inheriting as many existing properties as possible) with a few extra properties specific to map errors.

This change would be fundamental to how the [backend](https://github.com/osmlab/to-fix-backend) and frontend works but I think this is the best way of doing it and timing couldn't be better. We have upcoming projects that need to use to-fix and will be outputting ldgeojson.

---

I think we can literally use the simplestyle-spec to start this.
- each feature is on it's own line
- each feature is valid geojson
- features are styled and UI slightly modified based on simplestyle-spec properties found

@planemad - What do you think? Who in Bangalore is in a good spot to run this out with @Rub21 and I?

**Comment by ajithranka** [comment]
Beyond the GeoJSON specification, I think it will also be helpful if we can standardise the way we represent

- osm data (like feature type, id, tags, user details etc.), and
- relations.

Both these have been pain points when using generic GeoJSONs in Autochethan. Different tools we have output these in varying formats. As a standard, the format returned by [osmtogeojson](https://github.com/tyrasd/osmtogeojson) might be a good place to start.

I'm completely in for having the styling information as part of the GeoJSON. This would simply much of fiddly bits on the frontend. I have a few concerns about using the simplestyle-spec though:

- The spec doesn't map one-to-one with the GL style properties. If we are going to display these features on a GL map, there will be some fiddling required to map these to the correct GL paint properties.
- The spec is limited and doesn't include some useful things like labels (though we could repurpose `title` for that). Labels have been very useful when representing multiple features (like `from`, `via` and `to` as part of a turn restriction).

Would it be better if we use properties from the GL style spec directly instead of simplestyle?

**Comment by Rub21** [comment]
@aaronlidman @ajithranka @planemad 

I agree to standardize the import files to GeoJSON. I guess that every task will be created by each geojson file. Nice!

Couple of things:

- Standardize the `properties` maybe isn't really necessary, maybe we can do it with just a couple of features (id of the objects which intervene in an error) to recognize and then do a selection of this object JOSM or iD,  in case of `geometry` it is already established  for `Point`, `LineString` and `Polygon`.

- Handle the best way to serve the API for to-fix-plugin and to-fix-web. Some  features would be nice to serve for  to-fix-web but not necessarily for to-fix-plugin because it could turn slow the plugin.

- We need to figure out how to do more faster the transfer between to-fix-backend and clients (to-fix-plugin and to-fix-web), make a request to to-fix API + download data in JOSM or iD could spend a time, so I think is necessary to simplify the Geojson and reduce the features to display the error.

For example:

osmlint: unconnected-highways validator detects for an error two roads which are unconnected and a point where to display the exact point to resolve. The point contains the id of the objects that intervene in the error, so if we are going to transfer a bunch of data (two roads + a point) it could take time, so we need to filter the geojson with an exact errors to display.

osmlint: crossing-highways validator detects two roads and a point where the roads are in crossing, in this case also the API should serve just the point where the road are crossing.

So, for some issues, is not necessary to serve all context of the roads, only the point where to display the error, all context of roads we will get them in JOSM or iD when we start the edition. But I think it depends on what Geojson we will load in to-fix, maybe we can build a small tool to filter the exact features we want, but if the community wants to upload a geojson with high context it should work too. 

After talking with @ajith autochetan tool gets the Geojson file in once and load it, in the case of to-fix I think we should continue taking feature by feature as we are doing now  to take control  of  `fixed` and `not an error` issues.

**Comment by mvexel** [comment]
MapRoulette uses plain GeoJSON, it would be great if the formats would be interchangable.

**Comment by rodowi** [comment]
Here a JSON version of the CSV schemas proposed by @planemad 
https://gist.github.com/rodowi/0bd87524ee8c6c5594d7bffd1e5ea29a

- Basically the metadata lives in a separate JSON.
- Following the suggestions of @aaronlidman the project issues are listed as line-delimited GeoJSON features in a separate file. Issues can be grouped by project_id.
- I'm skipping the styling properties because I still don't understand the requirements on that front.

cc: @Rub21 

Any comments?

**Comment by ajithranka** [comment]
Switched to GeoJSONs for tasks.
