### ISSUE TITLE
Have more descriptive changeset comments

### ISSUE THREAD

**Issue by planemad** [osmlab/to-fix#151]
The automatic comments that to-fix provides for each task is not very descriptive for someone who is unfamiliar with the tool. This should better capture:
- What was the edit that was made
- What was the problem that was fixed

This helps local mappers better understand the context of the edit and provide more accurate feedback in case the fix was not appropriate.

Possibly related: https://github.com/osmlab/to-fix/issues/148

cc @Rub21 @samely @oini @srividyacb @jinalfoflia

**Comment by samely** [comment]
@planemad 

I consider that current comments are understandable because we had made some improvements based on community feedbacks (i.e [case 1](http://www.openstreetmap.org/changeset/37905675))

What I notice is that complaints in last feedbacks are not about the comments themselves, but about the comments that don't have sense due to the size of the bounding box like:
* [case 1](https://github.com/mapbox/data/issues/2033)
* [case 2](https://github.com/mapbox/data/issues/1937)
* [case ](http://www.openstreetmap.org/changeset/38959528)
* [extra case](https://github.com/mapbox/data/issues/2047) - not concern to-fix

I like Srividya's comments improvement.  I just think we should maintain the old comment structure with the **#** because this gives a fast idea of what was the fix about, and also this is really helpful for the team when doing peer review.

Based on Srividya's improvements I suggest:

Task | Changeset Comment
------------ | -------------
Broken Polygons | #to-fix:BrokenPolygons Fixing unclosed broken polygons considering https://github.com/mapbox/mapping/issues/206
Highways Intersects waterway |#to-fix:HighwayIntersectsWater Fixing overlapping highway and water features, by adding bridge, tunnel, layer or ford considering https://github.com/mapbox/mapping/issues/195
Kinks | #to-fix:Kinks Aligning and fixing impossible angles in highway considering https://github.com/mapbox/mapping/issues/107
Crossing highways | #to-fix:CrossingHighways Adding junction nodes or bridges to overlapping highways considering  https://github.com/mapbox/mapping/issues/104
Overlapping highways | #to-fix:OverlappingHighways Deleting overlapped highways considering https://github.com/mapbox/mapping/issues/167
Invalid turn-lanes | #to-fix:InvalidTurnLanes Fixing incorrectly added turn-lanes considering https://github.com/mapbox/mapping/issues/193
Missing layer bridges | #to-fix:MissingLayerBridges Adding missing layer tag to bridges considering https://github.com/mapbox/mapping/issues/201
Strange Layer | #to-fix:StrangeLayer Fixing incorrectly added layer tag to bridges and tunnels considering https://github.com/mapbox/mapping/issues/210
Missing oneway in motorway_link | #to-fix:MissingOnewaysMotorwayLink Adding missing oneway tag to motorway_links considering https://github.com/mapbox/mapping/issues/204
Self-intersecting Ways | #to-fix:SelfIntersectingWays Splitting self-intersecting highways considering https://github.com/mapbox/mapping/issues/203
Mixed layer | #to-fix:MixedLayer Fixing invalid layer tag in intersected highways considering https://github.com/mapbox/mapping/issues/202

cc @lxbarth  @Rub21

**Comment by planemad** [comment]
@samely the task name does not explain what was edited to local mappers, which is a problem. This is mentioned in both comments:
- http://www.openstreetmap.org/changeset/39721595
- http://www.openstreetmap.org/changeset/37905675

`#to-fix:MissingOnewaysMotorwayLink` in the beginning of the comment is not very useful for local mappers to understand the edit, it is better to have it on the end. Helping local mappers to validate the edit is more important than peer review.

Ref: [Comment suggestions](https://gist.github.com/srividyacb/f6c74456deaf5847037765cf1117a1de)

**Comment by samely** [comment]
@planemad 
I agree with you, for the team it really doesn't matter where the **#** is. But from [comment suggestions](https://gist.github.com/srividyacb/f6c74456deaf5847037765cf1117a1de) I understood that de last part should be just **#tofix**. 

This is how the changeset comments will look like:

Task | Changeset Comment
------------ | -------------
Broken Polygons | Fixing unclosed broken polygons considering #to-fix:BrokenPolygons https://github.com/mapbox/mapping/issues/206
Highways Intersects waterway | Fixing overlapping highway and water features, by adding bridge, tunnel, layer or ford considering #to-fix:HighwayIntersectsWater https://github.com/mapbox/mapping/issues/195
Kinks | Aligning and fixing impossible angles in highway considering #to-fix:Kinks https://github.com/mapbox/mapping/issues/107
Crossing highways | Adding junction nodes or bridges to overlapping highways considering  #to-fix:CrossingHighways https://github.com/mapbox/mapping/issues/104
Overlapping highways | Deleting overlapped highways considering  #to-fix:OverlappingHighways https://github.com/mapbox/mapping/issues/167
Invalid turn-lanes | Fixing incorrectly added turn-lanes considering #to-fix:InvalidTurnLanes https://github.com/mapbox/mapping/issues/193
Missing layer bridges | Adding missing layer tag to bridges considering   #to-fix:MissingLayerBridges  https://github.com/mapbox/mapping/issues/201
Strange Layer | Fixing incorrectly added layer tag to bridges and tunnels considering #to-fix:StrangeLayer https://github.com/mapbox/mapping/issues/210
Missing oneway in motorway_link | Adding missing oneway tag to motorway_links considering #to-fix:MissingOnewaysMotorwayLink https://github.com/mapbox/mapping/issues/204
Self-intersecting Ways | Splitting self-intersecting highways considering  #to-fix:SelfIntersectingWays https://github.com/mapbox/mapping/issues/203
Mixed layer | Fixing invalid layer tag in intersected highways considering  #to-fix:MixedLayer https://github.com/mapbox/mapping/issues/202

Per voice with @Rub21, broken polygons task is kind special, because most of the issues are about relations that include many objects.  We were thinking about getting automatically the name or type of the edited objects so we can add it to the comment. Or do you think it's enough to improve a bit more this comment?

**Comment by srividyacb** [comment]
@samely 👍 I have few suggestions here:

- As we are linking to the respective ticket links to the changeset comment, I think its not necessary to use task name again in the hash tag. Specifying only `#to-fix` will be good as that defines the source where tasks are hosted. 
- Also I would suggest to comment as `using #to-fix` and not `considering to-fix` as `considering` word may not reflect a confident changeset comment. 

@planemad @maning thoughts?

**Comment by planemad** [comment]
@srividyacb @samely 👍 the ticket link has the task name and link to to fix as well

**Comment by planemad** [comment]
Per voice w/ @samely the broken polygons comment is not very clear, here is my suggestion:

`Fixing invalid multipolygon relation by fixing unclosed rings and self intersecting areas using #to-fix mapbox/mapping#206`

cc @srividyacb

**Comment by samely** [comment]
I've already updated the comments.
