### ISSUE TITLE
Issues: to-fix

### ISSUE THREAD

**Issue by srividyacb** [osmlab/to-fix#79]
@aaronlidman Capturing one of the most occurring imagery series in to-fix.
As you can see in the below gif, this series of imageries(of same places) keeps flashing after fixing some number of to-fix issues. And these issues doesn't seem to be a unconnected major error. Later on it detects one of the unconnected major error and stops flashing.

![series](https://cloud.githubusercontent.com/assets/3423533/6709729/8fa4e19e-cda1-11e4-83d9-147bbf252ce5.gif)

@lxbarth @geohacker @planemad @ruthmaben @shravan91

**Comment by tristen** [comment]
Not re-creating this issue in the upcoming [react branch](https://github.com/osmlab/to-fix/tree/react). When this is merged hopefully this issue goes away.

**Comment by aaronlidman** [comment]
Ok, I see what is going on.

To explain, each of the unconnected errors is made up of two parts. A node id and a way id. The details for both must be retrieved from the OSM API, but if either of them fails (because it was changed or removed or something), the task will skip to the next item. I will remove this skipping functionality and see if the errors are still good without it. I'll update here when I remove the skipping.

**Comment by planemad** [comment]
@aaronlidman any idea if the osmi data is actually updated daily. A lot of the errors fixed yesterday are still showing up on [this map](https://api.tiles.mapbox.com/v4/planemad.c2f80b8f/page.html?access_token=pk.eyJ1IjoicGxhbmVtYWQiLCJhIjoiemdYSVVLRSJ9.g3lbg_eN0kztmsfIPxa9MQ#4/40.61/-100.63) that I updated with the latest data.

The total row count in the csv today is 50490. Will check this tomorrow.

**Comment by aaronlidman** [comment]
@planemad Sometimes. In my experience the data wasn't updated very consistent. It wasn't uncommon for me to find things fixed weeks ago.

**Comment by aaronlidman** [comment]
@srividyacb I found and fixed the problem. You should only see skipping rarely now. Let me know again if you see it lots like you did before.

**Comment by srividyacb** [comment]
thank you @aaronlidman
